import Head from "next/head";
import Hero from "../components/Hero";
import Reviews from "../components/Reviews";
import ServicePreview from "../components/ServicePreview";
import Slider from "../components/Slider";
import StickyHeader from "../components/StickyHeader";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Radiant Skin And Beauty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Radiant Skin & Beauty"
        message="A personal approach to produce the best results possible"
      />
      {/* <script src="https://apps.elfsight.com/p/platform.js" defer></script>
      <div class="elfsight-app-b0a1f521-3382-4fc1-b03d-cf10975e8cad"></div> */}
      <ServicePreview />
      <Reviews />
    </div>
  );
}
